--- 
rdf_connection_file: rdfstore
ardf_log_level: 0
local_uri: http://localhost:5000/
default_namespace_uri: http://default.dummy/
standalone_db: true
db_file: database
thumb_options: 
  height: "200"
  width: "200"
namespaces: 
  dcns: http://purl.org/dc/elements/1.1/
  dct: http://purl.org/dc/terms/
  dcmit: http://purl.org/dc/dcmitype/
  hyper: http://www.hypernietzsche.org/ontology/
  dive: http://purl.org/divenire/onto#
  taliadom: http://trac.talia.discovery-project.eu/wiki/SampleDomainOntology#
  foaf: http://xmlns.com/foaf/0.1/
  skos: http://www.w3.org/2004/02/skos/core#
  luccadom: http://trac.talia.discovery-project.eu/wiki/LuccaOntology#
  talias: http://trac.talia.discovery-project.eu/wiki/StructuralOntology#
  swicky: http://discovery-project.eu/ontologies/philoSpace/
  discovery: http://discovery-project.eu/ontologies/scholar/0.1/
  wordnet: http://xmlns.com/wordnet/1.6/
  geo: http://www.w3.org/2003/01/geo/wgs84_pos#
  demo: http://ontologies.muruca.org/demo3#
site_name: TALIA DEMO3
iip_root_directory_location: iip_root
data_directory_location: data
iip_server_uri: http://localhost:/fcgi-bin/iipsrv.fcgi
vips_command: /usr/local/bin/vips
convert_command: /usr/local/bin/convert